import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ---------------------------------------------------------------------------
// Report PDF Generator
//
// Generates clean A4 PDFs from report data for download.
// Styled for professional business review presentation.
// ---------------------------------------------------------------------------

interface ReportKpi {
  label: string;
  value: number;
  unit: string;
  change: number | null;
}

interface ReportData {
  id: string;
  cycle: string;
  periodStart: string;
  periodEnd: string;
  section: string;
  title: string;
  generatedAt: string;
  kpis: ReportKpi[];
  trends: string[];
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function formatKpiValue(value: number, unit: string): string {
  if (unit === "%") return `${value}%`;
  if (unit === "B") return `IDR ${value}B`;
  if (unit === "M") return `IDR ${value}M`;
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`;
  if (value >= 1_000) return `${(value / 1_000).toFixed(1)}K`;
  return value.toLocaleString();
}

export function generateReportPdf(report: ReportData): void {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // ── Header ──
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("CONFIDENTIAL — INTERNAL USE ONLY", margin, y);
  doc.text(
    `Generated: ${formatDate(report.generatedAt)}`,
    pageWidth - margin,
    y,
    { align: "right" }
  );
  y += 8;

  // ── Title ──
  doc.setFontSize(18);
  doc.setTextColor(30, 30, 30);
  doc.setFont("helvetica", "bold");
  doc.text("Honest Bank", margin, y);
  y += 8;

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(report.title, margin, y);
  y += 6;

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(
    `${report.section} · ${report.cycle.charAt(0).toUpperCase() + report.cycle.slice(1)} · ${formatDate(report.periodStart)} – ${formatDate(report.periodEnd)}`,
    margin,
    y
  );
  y += 10;

  // ── Divider ──
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // ── KPI Table ──
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.setFont("helvetica", "bold");
  doc.text("Key Performance Indicators", margin, y);
  y += 6;

  const kpiRows = report.kpis.map((kpi) => {
    const changeStr =
      kpi.change === null || kpi.change === 0
        ? "—"
        : `${kpi.change > 0 ? "+" : ""}${kpi.change}%`;
    const direction =
      kpi.change === null || kpi.change === 0
        ? ""
        : kpi.change > 0
          ? "▲"
          : "▼";
    return [kpi.label, formatKpiValue(kpi.value, kpi.unit), `${direction} ${changeStr}`];
  });

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value", "Change vs Prior"]],
    body: kpiRows,
    margin: { left: margin, right: margin },
    theme: "grid",
    headStyles: {
      fillColor: [91, 34, 255],
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [40, 40, 40],
    },
    alternateRowStyles: {
      fillColor: [248, 248, 252],
    },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 50, halign: "right", fontStyle: "bold" },
      2: { cellWidth: 45, halign: "center" },
    },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 10;

  // ── Key Trends ──
  if (report.trends.length > 0) {
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    doc.setFont("helvetica", "bold");
    doc.text("Key Trends & Observations", margin, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);

    for (const trend of report.trends) {
      // Check if we need a new page
      if (y > 260) {
        doc.addPage();
        y = margin;
      }

      doc.text("•", margin, y);
      const lines = doc.splitTextToSize(trend, contentWidth - 8);
      doc.text(lines, margin + 6, y);
      y += lines.length * 4.5 + 2;
    }
  }

  y += 8;

  // ── Footer divider ──
  if (y > 250) {
    doc.addPage();
    y = margin;
  }
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "This report was generated by Honest Business Reviews. Data sourced from BigQuery (storage-58f5a02c).",
    margin,
    y
  );
  y += 3.5;
  doc.text(
    "Product type: Regular (default). RP1 and Registration Fee excluded unless explicitly selected in filters.",
    margin,
    y
  );

  // ── Page numbers ──
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  // ── Save ──
  const filename = `honest-${report.cycle}-${report.periodStart}-${report.section.toLowerCase().replace(/\s+/g, "-")}.pdf`;
  doc.save(filename);
}
